### ISSUE TITLE
Linker Not Found

### ISSUE THREAD

**Issue by Samarth-SP** [TheLostLambda/ftc_http#2]
Hello Creators, 
    We were trying to use this service, and while building it using Cargo, we got an error saying that a linker was not found. Help would be appreciated!
Thanks,
deCoders FTC 14368
decodersftc.com
@decodersftc

**Comment by tejasthy** [comment]
Getting the same problem as @Samarth-SP. I can post an image if necessary.
deCoders FTC 14368

**Comment by TheLostLambda** [comment]
Hello and thank you for opening an issue!

Could you let me know which platform you are trying to build on and send some screenshots of the commands you are running and the errors being returned?

Additionally, upon attempting to rebuild this morning, I discovered that the rapid pace of Rust left this project a little ways behind. I pushed a new commit that adds some version requirements to the build. As of now, this builds for me on the latest Rust / Cargo version.

Could you try building this new version (be sure to run `rustup update` to update Rust and `git pull` to update this repo first) and let me know if the issue persists?

PS. In the meantime, are you able to use one of the precompiled binaries?

Thanks!
Brooks J Rady

**Comment by tejasthy** [comment]
Hi,
We tried to run the program on a Mac and a Windows computer. Additionally, we are trying to use the program with Atom. We are going to give program a go and will send you a message back. Thank you for your help. @Samarth-SP is going to send a couple screenshots as well.
Thanks,
deCoders FTC 14368
decodersftc.com
@deCodersftc

**Comment by Samarth-SP** [comment]
Hello Brooks J Rady,
   I pulled the new material, updated rust, and ran the build. I ended up running into the same issue, which I have sent a screenshot of in this message. I was running the build on Windows in the Command Prompt, and was in the folder ftc_http-master. 
Thanks you for your help!
deCoders FTC 14368
decodersftc.com
@deCodersFTC
https://user-images.githubusercontent.com/43121430/57736851-5feece00-765e-11e9-93c7-cfbe94689d28.png

**Comment by tejasthy** [comment]
Hello Brooks J Rady,
@Samarth-SP and I tried the new code and had some issues. In the video demonstration that you referenced in your documentation, you say that typing the function `ftc_http_osx ftc_http -v` should show the file version as long as you had downloaded it on your computer. On @Samarth-SP's windows computer it seemed to work. However, on my mac, it did not work and we are having trouble figuring out why. Help would be appreciated.
Thanks,
deCoders FTC 14368
decodersftc.com
@deCodersFTC
<img width="1440" alt="Screen Shot 2019-05-14 at 8 27 00 PM" src="https://user-images.githubusercontent.com/43117594/57746578-a8ba7d00-7686-11e9-8810-6d6df93dfe76.png">

**Comment by TheLostLambda** [comment]
I think to fix the Windows Build issue, you will need to install some version of the Microsoft build tools? [This link should be the download you need](https://www.microsoft.com/en-us/download/details.aspx?id=48159)

As for the OSX binary, make sure that you are in the same directory as the executable (be sure it is listed when you type `ls`) and that the file is marked as executable. If the file is called `ftc_http_osx` and it in your current directory (appears in the `ls` output), then you can make it executable with `chmod +x ftc_http_osx`. To check it worked, you can type `./ftc_http_osx -v`. The `./` is important and only works if the file in in the current directory. Also, you don't need to type `ftc_http` a second time.

That's a lot, but let me know if it helps with either the building or running on Mac issues!

I'll be here if you have any more questions!

**Comment by tejasthy** [comment]
Hi,
Just wanted to let you know that your solution worked and we are now able to successfully use your code. Thank you for your help and thank you for creating this code.
Thanks,
deCoders Robotics 14368
decodersftc.com
@deCodersFTC

**Comment by TheLostLambda** [comment]
I hope it helps your team! I'll close this issue now, but if you have any suggestions for improving the program or have any other questions, feel free to open another issue!

Best of luck!
