### ISSUE TITLE
How to install on MacOS Mojave ? With the file.

### ISSUE THREAD

**Issue by NotMoni** [TheLostLambda/ftc_http#3]

**Comment by TheLostLambda** [comment]
Hi! Sorry for the delay in the response, are you using the Safari browser? Your issue may be similar to the previously solved issue here: https://github.com/TheLostLambda/ftc_http/issues/1#issuecomment-466679355

If that seems like the issue, then this should be a copy-paste, working solution:
```
curl -L -O https://github.com/TheLostLambda/ftc_http/releases/download/v1.3.0/ftc_http_osx
chmod +x ftc_http_osx
./ftc_http_osx -h
```

If this doesn't solve your issue, please let me know how I can help further!

**Comment by TheLostLambda** [comment]
Hello @MoniS10,

Have you had the chance to try things out again? Do you still need help getting things working?

If so, let me know what I can do to help. If I don't hear back in a week or two, I'll assume you've solved your problem and close the issue.

I'd love to know how you are getting on!
Brooks J Rady

**Comment by TheLostLambda** [comment]
Closing the issue as I haven't heard anything back in a couple of weeks. Please open a new issue with details if your problem persists.

**Comment by NotMoni** [comment]
Hey
i need help

**Comment by TheLostLambda** [comment]
Hi, could you provide some detail regarding the nature of your problem?

**Comment by NotMoni** [comment]
I am using macOS Cataline. I have followed the directions you said and now I want to add it to PATH
so i can use it.

**Comment by NotMoni** [comment]
How do i add the program to PATH or where ever its need to be to run in all folders.

**Comment by NotMoni** [comment]
Right now I have to file in my Desktop and your steps work. But when i run `ftc_http_osx` in my onbot-java folder it says **command not found** . I am using Bash 5.0

**Comment by NotMoni** [comment]
@TheLostLambda add me on discord if you have it. Moni#1410

**Comment by TheLostLambda** [comment]
Yes, you want to add the program to your PATH. This link should help some:
https://www.architectryan.com/2012/10/02/add-to-the-path-on-mac-os-x-mountain-lion/

That should work for Catalina, but let me know if it doesn't and there are some other things we could try.
