### ISSUE TITLE
This need documentation.

### ISSUE THREAD

**Issue by NotMoni** [TheLostLambda/ftc_http#9]
I can i make documentation for this and send it via a PR?

**Comment by NotMoni** [comment]
@TheLostLambda

**Comment by TheLostLambda** [comment]
Sorry for the delay in getting back to you. You are more than welcome to put together some documentation if you'd like, but I can't guarantee that it will be merged. Documenting the code would require quite a bit of knowledge in Rust, but if you think there is a lack of user-facing documentation, please let me know!

**Comment by NotMoni** [comment]
Alright Mate. I will get started.
